[[armadillo]]
arch = "i686"
git-tree-sha1 = "9ec0a3021f80b15223a1d4d4a8abd50c342cf99a"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "6261da90be8a7b43d7069622d53f16e79b4dc636c7d6d8ae3ec3329029b53b9c"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "5ff1ee741fd751a997713ec5969ab09b0d016dd3"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "9ed493d140b1f4a997252ff52073633d797b64915560fc10637ead9517ba746d"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "32716a7b75018b01e607ed44f367f86cb3ccc7d7"
os = "macos"

    [[armadillo.download]]
    sha256 = "3154b70b255982f3ef682a9aa3d8e36284d737b035ff352b749b3bd91be2907b"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-apple-darwin14.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "08742d2a2e431549b8be59e095fe3fd9c8aa319c"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "cef6bba6ed0f2651ec650f63475572c97c41090bab980466fa105ab1f12f70e0"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "8f2be296874c2529e5c1059d88c84c24d8654e2a"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "5852341f77fde2e16f3e971d23c762dfa86085b1be06171180a148b8688d30b4"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "9f01f60485684df3304d0fdb2c33e0a44259e117"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "8eace1eaee27618a360fa583c284e938de459247901f9d34493e384f3d55aeb6"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "2c7a517d8fac13a84a757b967de0573ec4bd3856"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "742da6d071b1f2c1f62cf576967d6103046bf9f64707efd7fdcab0878863a1c2"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "66d6ba713e47e5315a92b5776b894c1bef494186"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "6342cb30bda4e465521d046b76b161ce39707ced6e29c5fdbe1fd5794e600e9f"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "de7e8f6602f8967c8dc06e0ef6c36372c13b5259"
os = "windows"

    [[armadillo.download]]
    sha256 = "6087ba2afdebf928198c9c2aea772031da89895cccfa5fc00eb116452d054fef"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "fa7150412a81e79fc5aad5619ffb43d37fb5c861"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "550db69cffe68081bbfb4d689a67386d5afb865a04972c235bc2ea75f38526b9"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-unknown-freebsd11.1.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "3e34777fa6ea6d8ce24794147eaa4412b8179d3c"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "d83792f9bdbf889e191d90d46f13d7b69a08fba6943806a75e9ad4967d3633e9"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "14ee79084970e61fa52e3a23d29da074040cdbad"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "cbd7765f0524c9f17a9e8a10ab2e99a7a3c8d2fe8077e5957cc8feb117be1bb6"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "4e07c6f0af31357a51ea92e07d24ea3bc61ebf44"
os = "windows"

    [[armadillo.download]]
    sha256 = "be802f40b7be761f5c82abf6f3c87002af592f1c87a4e3ad360a44b70b979af6"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-w64-mingw32.tar.gz"
