[[armadillo]]
arch = "i686"
git-tree-sha1 = "d76cd43c60d267ea62ed8b39cc1e72c7706efd80"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "004f443425d104f6a345b6218d147e3d5a55eb1868af3326e9bcd7d2df800a26"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "1990f29062e170bfb439922be0a61283833fb686"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "3d1205ef5643c4d440d934271bfb7fd1a1b48d23bc3ed4ad2d293328f5c71aa3"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "64835d58d4f02f4f19d365106aabd7685a801947"
os = "macos"

    [[armadillo.download]]
    sha256 = "c96e0bce8c9f323eda6b340d2ec6dbf280601648a8d3ab627ced5fc532d4e357"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.x86_64-apple-darwin14.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "58012d0b41d182059332d6beb77541e3f820ab70"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "8ebd80b42e5e6b1b509b75404bc467e55a64cb23c7b29e6934744708254cddfe"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "6a491063779e6d414b898a15ca18ac1600d9199e"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "527263503aa4f04a60cbd0458d384cd8bdad8df36e3ef72e1a95447e9737a8bd"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "986d04a040b9cf468b4ff450dacd792a20f24f1b"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "e092afdc78e6aed3deaa13697270c477937127868ed1522a8f8ed710d4a42202"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "97069a6fd15146d9f5e970cf443df52c6d6d74ad"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "7016b33f9c9973a4330b8e571f0386e06d89348d7768c78fc905b3f4696ade03"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "20f270107bfa1e371ed20af85a02765940d6b887"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "c57b89b056f8d56be69baf2b616ea6b97711dda3667ff77c74ac2b9aef9cacac"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.arm-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "bcbeb72e05afbb0f24fe53a524b42f3c2074a760"
os = "windows"

    [[armadillo.download]]
    sha256 = "41302355589e2bb9521bad962d8b4a35ca1a492bc577ee70a9e1d4ad29137f05"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "20f2a510ba53b8e2290f56e4120285ca0f1a1d91"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "b9618ecc2781e1f6b8d53167da1a316c63c24b2b6a594f31f44322ff9bcfb94f"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.x86_64-unknown-freebsd11.1.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "da66e1dab73109155ce3a07a61c5d348a5d41406"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "70acc7855189e6da1657f3485fe3927b8398cd078418e1c53be93bd6f5fa9834"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.arm-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "a0513b6c0643cba79eb5c75fef983f23df354d78"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "beb235b868b1c8adee065190cb064dd15dca5f37d7b045e415bee4435136354a"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "dd64b298cd686d196ed2834e5a2a284bd11036dd"
os = "windows"

    [[armadillo.download]]
    sha256 = "20c1f2b45c78f55fc3dfd520dbadb771ce5d59ca1e2e5f32e22e95e9062d6b09"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.2+0/armadillo.v9.850.2.x86_64-w64-mingw32.tar.gz"
