[[armadillo]]
arch = "i686"
git-tree-sha1 = "c5fbbc7e5c3d6cf2ea3afb93b27d27388336e9b6"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "dffc39ffd15493eff655d3eb0fbc32497d8acd2bbf6af193cb24c825854229b6"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "40910170da1fe21aa18819939b80abdcc6cfa976"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "2cc0a99bb0c8857e389740db7ad6f25b3a5c796c1e901dbe5f16db59876b83c7"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "fc0a6833670ab611791e219e8bdca70a6e5cad66"
os = "macos"

    [[armadillo.download]]
    sha256 = "cd83745cc3f641ddbab4f5fb0c983fa57752101050a4cfbda7f175b6d8e458cc"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-apple-darwin14.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "955259d09c94763f01e5b561e5e612809840573d"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "ecc1612323a17614490841427b6152ee37dea38dc66cbb7d7f6a3818633ef0ff"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "20572b6d6b1c3af160b349c0f6b291a584a0a150"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "a23da1a9324b6ad51254bd6992c827f1a72b974c7613d3778ed7fef98b2ac691"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "e3c77a29c5fc99e090ace1beff56accdafb40ca5"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "fcca108397e27bbfd6bff8c02680c4e08dae00876371b5b4525fd5dc0110ff7e"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "79317f68a39f636a835936f7e310500b514d8867"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "85a5fb21ecb7fd986663d56fc02695c3e4e59e0fbb63073ae8ffc3e0a866fb9d"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "254be383c12c7809cb2fc402cfc5689e89b490ea"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "023ff22894f9a54fa21e8cf4116229cd18295b1c9d32330324a0cd21fe91b5ef"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "ba50f82375cd77ce8d8e995dfa077e912c23065d"
os = "windows"

    [[armadillo.download]]
    sha256 = "88b5b3d42e4492fde44d7ef89099b1e7beae9fa7f44062484d02c7f2c0c95f14"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "9da53187cccd9035a67f3a2f07854d3e86e225a8"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "a9ff7a6a37d9dea40f13f11b6bb3e744c306e3f4702b31f16502704a2402b667"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-unknown-freebsd11.1.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "4504f590e949b53c6a1e7f72b10554fa3cb36ff8"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "e10babb05c8283afb637d85bb147498bcff08013b9b96f077923c7cb94d7064d"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "0ec0f22f2a77898e259fc825cde2ae4cbdb67269"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "570420a5852c80430cefc6ea4c6005a3ec59eb7bf11949b72980d0514a34447c"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "9333fa99ab243351d7fd5662921372b6824c34c4"
os = "windows"

    [[armadillo.download]]
    sha256 = "4fe6f83c3a165d77e7c7825fcf3b32369addb3292657d33bed3b09129278469b"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-w64-mingw32.tar.gz"
