[[armadillo]]
arch = "i686"
git-tree-sha1 = "666c1ba25279d796e6d1644c3b415dca803dc98f"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "853a2c1de73a7410f6acec86d5137454c5bd75aade3d2418d9c92af1ea7e3bc0"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "d0838d2e4615431421d420f8686ff23768aaaf71"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "5c11d9fd39898e5f53d42174336c8ed0341953660bfd53172e279d4b44dae77b"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "14b3decdc411c0e26a3960b4b685e1b947b3dd0d"
os = "macos"

    [[armadillo.download]]
    sha256 = "4252f5e330200d79f1135e90b494f7481ecd200ec07edf4d98cdc18374b21eb1"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-apple-darwin14.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "fcd9bbd569298680914306bfe4f116c23d501777"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "90889e527ac4e4efc8fb74becdc2bcd74ae5c55de98aecb539f87bfc8dbeb387"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "f333c5bd35d3a666ece132d3052758012ba122da"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "4245051201a1d6fadd685c449c22df259dc0d9ab2446239151549ce2d052de05"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "51fa1eaeea3572206b1e99919842f37bd7041280"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "827a450876802d8d9f36986b4e65b33416e5ccaaea111360a263cefdaede4d6d"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "5f5f21f0b294ffc5863376e652f02b81d13e0a94"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "1270180dc1cd058b7c3300d723fa3de7475949deccf58a12b9fefac540c46025"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "90de4cffcaeb3efc7250a653e8e79a7fe7884517"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "9cbd9a0a9483fae3ec64dcb70bdcb7332617a57572ca1217d75f5ed5ce2aab2f"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "393429d53d412a2ae8313fd21e0a2384202ae915"
os = "windows"

    [[armadillo.download]]
    sha256 = "dba4c3de539fc63f58c310c9402ff4b290644b017ce0d5e491eff0cada1124e4"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "3ec423dd0fbc772df3ae74e2b8b2892e2f56f2bf"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "7a48019a7f6895ec313c1507de18e1a4413f44431fcb1e7b5e2d03fb31674b1d"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-unknown-freebsd11.1.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "a817fd44d024a1872553a7a9e8c6622d47a4a96a"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "df6397f4c561edeb92eb84e7edfe5031e91e98399a6a5bf91f02881e4f2519a5"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "e8ab64947822123fd7921ef787ee49adc7899659"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "a8e3df8c24a68108d0080a07f871536fca79ad5670ed480694ec99ec4761ce57"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "d0de1d876d528a7f591413bdcf276c923c0a2b25"
os = "windows"

    [[armadillo.download]]
    sha256 = "2ae6509c439aac188d03aebf3117dbb0294ec1b9add266b563f6472b0c9a2df0"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-w64-mingw32.tar.gz"
