[[armadillo]]
arch = "i686"
git-tree-sha1 = "ad35e1a3a18ec45e37617f87a6dfdf0ca71b525f"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "f2564a2f0b45758775d17ba279b95a1d2476a0a724b3e7f4f8797c4ee171ac88"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-gnu.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "4e88dad82b6d3765c5b9749e4eb371890b205d3c"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "5d0480b0dd32df4f6da4b335763531badb61d1e2baae3c21bf2c8d2d246b50d5"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-linux-musl.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "d1efaec2bd34bbe802f5b311ffbf0f97450c1be6"
os = "macos"

    [[armadillo.download]]
    sha256 = "18a38e48652ce43f0a7a36c942931ee9683fe6efec30a8446536baf0c7ca8d96"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-apple-darwin14.tar.gz"
[[armadillo]]
arch = "powerpc64le"
git-tree-sha1 = "76f0d668d8e314ce6785a249b253339856ad81ca"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "0508f9c628397c95c051fea53acba0318428d436bc6fbc03922f47381ba8f3ff"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.powerpc64le-linux-gnu.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "ca42c8ab42734f3a921784b0f4a85322a01e68c6"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "d41cf58a1075c0c201bf4933063a1e1af20a79a301f7b6e62487c90a04ddadb5"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "d6ee5ef167fa9a284dae1603af96ad13d912216c"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "2e97a9675dbb6093e735773d2db8345a5236391fe49559c2a05ce9cfb014eecd"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-musl.tar.gz"
[[armadillo]]
arch = "aarch64"
git-tree-sha1 = "fa74be0569b2767f647d9b6cfa6114ef701ad8b5"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "e0e1877efc200f8cd5c372a619b97f8b2e520f49412fc383a37a64048a0fb044"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.aarch64-linux-musl.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "08c429db08440f756a93a9309550ae4299d647c4"
libc = "musl"
os = "linux"

    [[armadillo.download]]
    sha256 = "041db88208b8726be26722d1f6f514b3f206691144d7be0d77601b2df18b4619"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-musleabihf.tar.gz"
[[armadillo]]
arch = "i686"
git-tree-sha1 = "75050a3415c3c0a1923bc65ac6e4e8a6335bb8af"
os = "windows"

    [[armadillo.download]]
    sha256 = "9e93412cc346a69c60d6aed7c0c56f0d33aadf04b469364931127ec0e2be4971"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.i686-w64-mingw32.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "66c9a4ac296f18c61e51fb0a87854a77e9a84cf3"
os = "freebsd"

    [[armadillo.download]]
    sha256 = "97a620069df2cc21732f38bfdc96b24dcd9532de29db925dadc7651a8ef3d30c"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-unknown-freebsd11.1.tar.gz"
[[armadillo]]
arch = "armv7l"
git-tree-sha1 = "51975e446b3002024bf3618c4fe83458d959e575"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "bba3e3c53b37be012f95029c838e6f38814cd2dbd03b40d1dd104e5a900db0cb"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.arm-linux-gnueabihf.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "31b57e4551a4ea8a111fd25576c3d5dd692b0e28"
libc = "glibc"
os = "linux"

    [[armadillo.download]]
    sha256 = "13965da3364c024591314f8a1b5211bbb605941a2f629c2769abf8a4e95c8cb1"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-linux-gnu.tar.gz"
[[armadillo]]
arch = "x86_64"
git-tree-sha1 = "7013b00b4f55de8d1a22d51085b665cdd986a883"
os = "windows"

    [[armadillo.download]]
    sha256 = "699bdf54038c67b09de0612d03f531e8ee66f99b83bb2dea6acad4054d69be06"
    url = "https://github.com/rcurtin/armadillo_jll.jl/releases/download/armadillo-v9.850.1+2/armadillo.v9.850.1.x86_64-w64-mingw32.tar.gz"
